package com.github.pablowyourmind.equipment_catalogue.model;

import lombok.Data;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDate;
import java.util.List;

@Data
@Document(collection = "devices")
public class Device {
    private String id;
    private String name;
    private String manufacturer;
    private LocalDate purchaseDate;
    private Integer quantity;
    private Double totalPrice;
    private String status;
    private List<FileRef> files;

    // Constructors, getters, and setters can be generated by Lombok
}
